@ECHO OFF

TITLE generate.bat

IF "%1" EQU "0" SET IMACRONORMAL=ReCaptcha
IF "%1" EQU "0" SET IMACROPIRACY=NoReCaptcha
IF "%1" EQU "0" SET browserCacheDiskEnable=false
IF "%1" EQU "0" SET browserCacheMemoryCapacity=393216
IF "%1" EQU "0" SET NoReCaptchaIIM=FINISH
IF "%1" EQU "0" SET NoReCapViewIIM=VPNGATE
IF "%1" EQU "1" SET IMACRONORMAL=ReCaptcha
IF "%1" EQU "1" SET IMACROPIRACY=NoReCaptcha
IF "%1" EQU "1" SET browserCacheDiskEnable=true
IF "%1" EQU "1" SET browserCacheMemoryCapacity=196608
IF "%1" EQU "1" SET NoReCaptchaIIM=Ads_Skip_Bot_-_NoReCapView
IF "%1" EQU "1" SET NoReCapViewIIM=FINISH
IF "%1" EQU "2" SET IMACRONORMAL=NoReCapView
IF "%1" EQU "2" SET IMACROPIRACY=NoReCaptcha
IF "%1" EQU "2" SET browserCacheDiskEnable=true
IF "%1" EQU "2" SET browserCacheMemoryCapacity=196608
IF "%1" EQU "2" SET NoReCaptchaIIM=FINISH
IF "%1" EQU "2" SET NoReCapViewIIM=VPNGATE


ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO. []                                                    []
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO. 
IF /I NOT EXIST "%USERPROFILE%\Documents\iMacros" MKDIR "%USERPROFILE%\Documents\iMacros"
IF /I NOT EXIST "%USERPROFILE%\Documents\iMacros\Datasources" MKDIR "%USERPROFILE%\Documents\iMacros\Datasources"
IF /I NOT EXIST "%USERPROFILE%\Documents\iMacros\Macros" MKDIR "%USERPROFILE%\Documents\iMacros\Macros"
IF /I NOT EXIST "%USERPROFILE%\Documents\iMacros\Macros\iMacros" MKDIR "%USERPROFILE%\Documents\iMacros\Macros\iMacros"
COPY /Y "Z:\Database\Imacros\Datasources\*.CSV" "%USERPROFILE%\Documents\iMacros\Datasources"
COPY /Y "Z:\Database\Imacros\Macros\*.IIM" "%USERPROFILE%\Documents\iMacros\Macros"
COPY /Y "Z:\Database\Imacros\Datasources\Custom\*.CSV" "%USERPROFILE%\Documents\iMacros\Datasources"
COPY /Y "Z:\Database\Imacros\Macros\Custom\*.IIM" "%USERPROFILE%\Documents\iMacros\Macros"
COPY /Y "Z:\Database\ff\defaults\pref\*.JS" ".\ff\app\firefox\defaults\pref"
COPY /Y "Z:\Database\ff\mms.cfg" "%SYSTEMROOT%\SYSTEM32\Macromed\Flash\mms.cfg"
type "%USERPROFILE%\Documents\iMacros\Macros\Ads_Skip_Bot_-_NoReCaptcha.iim" | findrepl "NoReCaptchaIIM" "%NoReCaptchaIIM%" > "%USERPROFILE%\Documents\iMacros\Macros\Ads_Skip_Bot_-_NoReCaptcha.iimrename"
DEL /Q "%USERPROFILE%\Documents\iMacros\Macros\Ads_Skip_Bot_-_NoReCaptcha.iim"
REN "%USERPROFILE%\Documents\iMacros\Macros\Ads_Skip_Bot_-_NoReCaptcha.iimrename" "Ads_Skip_Bot_-_NoReCaptcha.iim"
type "%USERPROFILE%\Documents\iMacros\Macros\Ads_Skip_Bot_-_NoReCapView.iim" | findrepl "NoReCapViewIIM" "%NoReCapViewIIM%" > "%USERPROFILE%\Documents\iMacros\Macros\Ads_Skip_Bot_-_NoReCapView.iimrename"
DEL /Q "%USERPROFILE%\Documents\iMacros\Macros\Ads_Skip_Bot_-_NoReCapView.iim"
REN "%USERPROFILE%\Documents\iMacros\Macros\Ads_Skip_Bot_-_NoReCapView.iimrename" "Ads_Skip_Bot_-_NoReCapView.iim"
ECHO. 
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO. []                                                    []
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]

TIMEOUT 02 /NOBREAK

:USERJS
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO. []                                                    []
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO.
:REFERERVAULEDEFAULT
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEDEFAULT="http://google.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEDEFAULT="http://google.us"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEDEFAULT="http://yahoo.com"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEDEFAULT="http://image.google.com"
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEDEFAULT="http://image.google.us"
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEDEFAULT="http://us.yahoo.com"
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEDEFAULT="http://bing.com"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEDEFAULT="http://duckduckgo.com"
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEDEFAULT="http://facebook.com"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEDEFAULT="http://twitter.com"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEDEFAULT="http://m.facebook.com"
IF "%REFERERRANDOM%"=="12" SET REFERERVAULEDEFAULT="http://l.facebook.com"
IF "%REFERERRANDOM%"=="13" SET REFERERVAULEDEFAULT="http://m.google.com"
IF "%REFERERRANDOM%"=="14" SET REFERERVAULEDEFAULT="http://m.google.us"
IF "%REFERERRANDOM%"=="15" SET REFERERVAULEDEFAULT="http://l.messenger.com"
IF "%1" EQU "REBUILD" GOTO:EOF
:REFERERVAULEEMAIL
SET /A REFERERRANDOM=%RANDOM% %%5 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEEMAIL="http://hornyalwary.top"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEEMAIL="http://banit.me"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEEMAIL="http://nada.ltd"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEEMAIL="http://nada.email"
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEEMAIL="http://getnada.com"
IF "%1" EQU "REBUILD" GOTO:EOF
:REFERERVAULEHENTAI
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEHENTAI="http://xgallery-dump.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEHENTAI="http://g.e-hentai.org"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEHENTAI="http://xxxgallerydump.com"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEHENTAI="http://worldvoyeur.xyz"
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEHENTAI="http://xyzcomics.com"
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEHENTAI="http://pornhub.com"
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEHENTAI="http://hentaicore.net"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEHENTAI="http://hentaisun.net"
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEHENTAI="http://hentai-hot.com"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEHENTAI="http://hentai4daily.com"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEHENTAI="http://sexypins.net"
IF "%REFERERRANDOM%"=="12" SET REFERERVAULEHENTAI="http://urlgalleries.net"
IF "%REFERERRANDOM%"=="13" SET REFERERVAULEHENTAI="http://xxxporndump.urlgalleries.net"
IF "%REFERERRANDOM%"=="14" SET REFERERVAULEHENTAI="http://beautifulgirlspics.urlgalleries.net"
IF "%REFERERRANDOM%"=="15" SET REFERERVAULEHENTAI="http://ehentaimangagallerie.urlgalleries.net"
IF "%1" EQU "REBUILD" GOTO:EOF
:REFERERVAULEMULT1
CALL :GETREFHOSTS 371
FOR /F %%F IN ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Load.csv" ^| FIND /C "://"') DO SET /A CSVHOSTLOAD=%%F
FOR /F %%F IN ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Main.csv" ^| FIND /C ","') DO SET /A CSVHOSTMAIN=%%F
IF %CSVHOSTLOAD% LEQ 14 CALL :DATASOURCENOTENOUGH %GETREFHOSTS% %CSVHOSTLOAD% Refer
IF %CSVHOSTMAIN% LEQ 99 CALL :DATASOURCENOTENOUGH %GETREFHOSTS% %CSVHOSTMAIN% Lists
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF %REFERERRANDOM% GEQ 11 SET "GETREFERERS=GETREFERERSLOAD"
IF %REFERERRANDOM% LEQ 10 SET "GETREFERERS=GETREFERERSMAIN"
SET /A CSVHOSTLOAD=(%RANDOM%*%CSVHOSTLOAD%/32768)+1
SET /A CSVHOSTMAIN=(%RANDOM%*%CSVHOSTMAIN%/32768)+1
SET URLLISTVAULEMULT1=
SET REFERERVAULEMULT1=
CALL :%GETREFERERS% %CSVHOSTMAIN% URLLISTVAULEMULT1 REFERERVAULEMULT1 || CALL :DATASOURCEINCORRECT %GETREFHOSTS% %CSVHOSTMAIN% %URLLISTVAULEMULT1% %REFERERVAULEMULT1%
:REFERERVAULEMULT2
CALL :GETREFHOSTS 372
FOR /F %%F IN ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Load.csv" ^| FIND /C "://"') DO SET /A CSVHOSTLOAD=%%F
FOR /F %%F IN ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Main.csv" ^| FIND /C ","') DO SET /A CSVHOSTMAIN=%%F
IF %CSVHOSTLOAD% LEQ 14 CALL :DATASOURCENOTENOUGH %GETREFHOSTS% %CSVHOSTLOAD% Refer
IF %CSVHOSTMAIN% LEQ 99 CALL :DATASOURCENOTENOUGH %GETREFHOSTS% %CSVHOSTMAIN% Lists
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF %REFERERRANDOM% GEQ 11 SET "GETREFERERS=GETREFERERSLOAD"
IF %REFERERRANDOM% LEQ 10 SET "GETREFERERS=GETREFERERSMAIN"
SET /A CSVHOSTLOAD=(%RANDOM%*%CSVHOSTLOAD%/32768)+1
SET /A CSVHOSTMAIN=(%RANDOM%*%CSVHOSTMAIN%/32768)+1
SET URLLISTVAULEMULT2=
SET REFERERVAULEMULT2=
CALL :%GETREFERERS% %CSVHOSTMAIN% URLLISTVAULEMULT2 REFERERVAULEMULT2 || CALL :DATASOURCEINCORRECT %GETREFHOSTS% %CSVHOSTMAIN% %URLLISTVAULEMULT2% %REFERERVAULEMULT3%
:REFERERVAULEMULT3
CALL :GETREFHOSTS 373
FOR /F %%F IN ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Load.csv" ^| FIND /C "://"') DO SET /A CSVHOSTLOAD=%%F
FOR /F %%F IN ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Main.csv" ^| FIND /C ","') DO SET /A CSVHOSTMAIN=%%F
IF %CSVHOSTLOAD% LEQ 14 CALL :DATASOURCENOTENOUGH %GETREFHOSTS% %CSVHOSTLOAD% Refer
IF %CSVHOSTMAIN% LEQ 99 CALL :DATASOURCENOTENOUGH %GETREFHOSTS% %CSVHOSTMAIN% Lists
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF %REFERERRANDOM% GEQ 11 SET "GETREFERERS=GETREFERERSLOAD"
IF %REFERERRANDOM% LEQ 10 SET "GETREFERERS=GETREFERERSMAIN"
SET /A CSVHOSTLOAD=(%RANDOM%*%CSVHOSTLOAD%/32768)+1
SET /A CSVHOSTMAIN=(%RANDOM%*%CSVHOSTMAIN%/32768)+1
SET URLLISTVAULEMULT3=
SET REFERERVAULEMULT3=
CALL :%GETREFERERS% %CSVHOSTMAIN% URLLISTVAULEMULT3 REFERERVAULEMULT3 || CALL :DATASOURCEINCORRECT %GETREFHOSTS% %CSVHOSTMAIN% %URLLISTVAULEMULT3% %REFERERVAULEMULT3%
:REFERERVAULEMULT4
CALL :GETREFHOSTS 374
FOR /F %%F IN ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Load.csv" ^| FIND /C "://"') DO SET /A CSVHOSTLOAD=%%F
FOR /F %%F IN ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Main.csv" ^| FIND /C ","') DO SET /A CSVHOSTMAIN=%%F
IF %CSVHOSTLOAD% LEQ 14 CALL :DATASOURCENOTENOUGH %GETREFHOSTS% %CSVHOSTLOAD% Refer
IF %CSVHOSTMAIN% LEQ 99 CALL :DATASOURCENOTENOUGH %GETREFHOSTS% %CSVHOSTMAIN% Lists
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF %REFERERRANDOM% GEQ 11 SET "GETREFERERS=GETREFERERSLOAD"
IF %REFERERRANDOM% LEQ 10 SET "GETREFERERS=GETREFERERSMAIN"
SET /A CSVHOSTLOAD=(%RANDOM%*%CSVHOSTLOAD%/32768)+1
SET /A CSVHOSTMAIN=(%RANDOM%*%CSVHOSTMAIN%/32768)+1
SET URLLISTVAULEMULT4=
SET REFERERVAULEMULT4=
CALL :%GETREFERERS% %CSVHOSTMAIN% URLLISTVAULEMULT4 REFERERVAULEMULT4 || CALL :DATASOURCEINCORRECT %GETREFHOSTS% %CSVHOSTMAIN% %URLLISTVAULEMULT4% %REFERERVAULEMULT4%
:REFERERVAULETRAP1
CALL :GETREFHOSTS 347
FOR /F %%F IN ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Load.csv" ^| FIND /C "://"') DO SET /A CSVHOSTLOAD=%%F
FOR /F %%F IN ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Main.csv" ^| FIND /C ","') DO SET /A CSVHOSTMAIN=%%F
IF %CSVHOSTLOAD% LEQ 14 CALL :DATASOURCENOTENOUGH %GETREFHOSTS% %CSVHOSTLOAD% Refer
IF %CSVHOSTMAIN% LEQ 99 CALL :DATASOURCENOTENOUGH %GETREFHOSTS% %CSVHOSTMAIN% Lists
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF %REFERERRANDOM% GEQ 11 SET "GETREFERERS=GETREFERERSLOAD"
IF %REFERERRANDOM% LEQ 10 SET "GETREFERERS=GETREFERERSMAIN"
SET /A CSVHOSTLOAD=(%RANDOM%*%CSVHOSTLOAD%/32768)+1
SET /A CSVHOSTMAIN=(%RANDOM%*%CSVHOSTMAIN%/32768)+1
SET URLLISTVAULETRAP1=
SET REFERERVAULETRAP1=
CALL :%GETREFERERS% %CSVHOSTMAIN% URLLISTVAULETRAP1 REFERERVAULETRAP1 || CALL :DATASOURCEINCORRECT %GETREFHOSTS% %CSVHOSTMAIN% %URLLISTVAULETRAP1% %REFERERVAULETRAP1%
:REFERERVAULETRAP2
CALL :GETREFHOSTS 348
FOR /F %%F IN ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Load.csv" ^| FIND /C "://"') DO SET /A CSVHOSTLOAD=%%F
FOR /F %%F IN ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Main.csv" ^| FIND /C ","') DO SET /A CSVHOSTMAIN=%%F
IF %CSVHOSTLOAD% LEQ 14 CALL :DATASOURCENOTENOUGH %GETREFHOSTS% %CSVHOSTLOAD% Refer
IF %CSVHOSTMAIN% LEQ 99 CALL :DATASOURCENOTENOUGH %GETREFHOSTS% %CSVHOSTMAIN% Lists
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF %REFERERRANDOM% GEQ 11 SET "GETREFERERS=GETREFERERSLOAD"
IF %REFERERRANDOM% LEQ 10 SET "GETREFERERS=GETREFERERSMAIN"
SET /A CSVHOSTLOAD=(%RANDOM%*%CSVHOSTLOAD%/32768)+1
SET /A CSVHOSTMAIN=(%RANDOM%*%CSVHOSTMAIN%/32768)+1
SET URLLISTVAULETRAP2=
SET REFERERVAULETRAP2=
CALL :%GETREFERERS% %CSVHOSTMAIN% URLLISTVAULETRAP2 REFERERVAULETRAP2 || CALL :DATASOURCEINCORRECT %GETREFHOSTS% %CSVHOSTMAIN% %URLLISTVAULETRAP2% %REFERERVAULETRAP2%
:REFERERVAULETRAP3
CALL :GETREFHOSTS 349
FOR /F %%F IN ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Load.csv" ^| FIND /C "://"') DO SET /A CSVHOSTLOAD=%%F
FOR /F %%F IN ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Main.csv" ^| FIND /C ","') DO SET /A CSVHOSTMAIN=%%F
IF %CSVHOSTLOAD% LEQ 14 CALL :DATASOURCENOTENOUGH %GETREFHOSTS% %CSVHOSTLOAD% Refer
IF %CSVHOSTMAIN% LEQ 99 CALL :DATASOURCENOTENOUGH %GETREFHOSTS% %CSVHOSTMAIN% Lists
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF %REFERERRANDOM% GEQ 11 SET "GETREFERERS=GETREFERERSLOAD"
IF %REFERERRANDOM% LEQ 10 SET "GETREFERERS=GETREFERERSMAIN"
SET /A CSVHOSTLOAD=(%RANDOM%*%CSVHOSTLOAD%/32768)+1
SET /A CSVHOSTMAIN=(%RANDOM%*%CSVHOSTMAIN%/32768)+1
SET URLLISTVAULETRAP3=
SET REFERERVAULETRAP3=
CALL :%GETREFERERS% %CSVHOSTMAIN% URLLISTVAULETRAP3 REFERERVAULETRAP3 || CALL :DATASOURCEINCORRECT %GETREFHOSTS% %CSVHOSTMAIN% %URLLISTVAULETRAP3% %REFERERVAULETRAP3%
:REFERERVAULETRAP4
CALL :GETREFHOSTS 350
FOR /F %%F IN ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Load.csv" ^| FIND /C "://"') DO SET /A CSVHOSTLOAD=%%F
FOR /F %%F IN ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Main.csv" ^| FIND /C ","') DO SET /A CSVHOSTMAIN=%%F
IF %CSVHOSTLOAD% LEQ 14 CALL :DATASOURCENOTENOUGH %GETREFHOSTS% %CSVHOSTLOAD% Refer
IF %CSVHOSTMAIN% LEQ 99 CALL :DATASOURCENOTENOUGH %GETREFHOSTS% %CSVHOSTMAIN% Lists
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF %REFERERRANDOM% GEQ 11 SET "GETREFERERS=GETREFERERSLOAD"
IF %REFERERRANDOM% LEQ 10 SET "GETREFERERS=GETREFERERSMAIN"
SET /A CSVHOSTLOAD=(%RANDOM%*%CSVHOSTLOAD%/32768)+1
SET /A CSVHOSTMAIN=(%RANDOM%*%CSVHOSTMAIN%/32768)+1
SET URLLISTVAULETRAP4=
SET REFERERVAULETRAP4=
CALL :%GETREFERERS% %CSVHOSTMAIN% URLLISTVAULETRAP4 REFERERVAULETRAP4 || CALL :DATASOURCEINCORRECT %GETREFHOSTS% %CSVHOSTMAIN% %URLLISTVAULETRAP4% %REFERERVAULETRAP4%
:REFERERVAULETRAP5
CALL :GETREFHOSTS 351
FOR /F %%F IN ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Load.csv" ^| FIND /C "://"') DO SET /A CSVHOSTLOAD=%%F
FOR /F %%F IN ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Main.csv" ^| FIND /C ","') DO SET /A CSVHOSTMAIN=%%F
IF %CSVHOSTLOAD% LEQ 14 CALL :DATASOURCENOTENOUGH %GETREFHOSTS% %CSVHOSTLOAD% Refer
IF %CSVHOSTMAIN% LEQ 99 CALL :DATASOURCENOTENOUGH %GETREFHOSTS% %CSVHOSTMAIN% Lists
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF %REFERERRANDOM% GEQ 11 SET "GETREFERERS=GETREFERERSLOAD"
IF %REFERERRANDOM% LEQ 10 SET "GETREFERERS=GETREFERERSMAIN"
SET /A CSVHOSTLOAD=(%RANDOM%*%CSVHOSTLOAD%/32768)+1
SET /A CSVHOSTMAIN=(%RANDOM%*%CSVHOSTMAIN%/32768)+1
SET URLLISTVAULETRAP5=
SET REFERERVAULETRAP5=
CALL :%GETREFERERS% %CSVHOSTMAIN% URLLISTVAULETRAP5 REFERERVAULETRAP5 || CALL :DATASOURCEINCORRECT %GETREFHOSTS% %CSVHOSTMAIN% %URLLISTVAULETRAP5% %REFERERVAULETRAP5%
:REFERERVAULETRAP6
CALL :GETREFHOSTS 352
FOR /F %%F IN ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Load.csv" ^| FIND /C "://"') DO SET /A CSVHOSTLOAD=%%F
FOR /F %%F IN ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Main.csv" ^| FIND /C ","') DO SET /A CSVHOSTMAIN=%%F
IF %CSVHOSTLOAD% LEQ 14 CALL :DATASOURCENOTENOUGH %GETREFHOSTS% %CSVHOSTLOAD% Refer
IF %CSVHOSTMAIN% LEQ 99 CALL :DATASOURCENOTENOUGH %GETREFHOSTS% %CSVHOSTMAIN% Lists
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF %REFERERRANDOM% GEQ 11 SET "GETREFERERS=GETREFERERSLOAD"
IF %REFERERRANDOM% LEQ 10 SET "GETREFERERS=GETREFERERSMAIN"
SET /A CSVHOSTLOAD=(%RANDOM%*%CSVHOSTLOAD%/32768)+1
SET /A CSVHOSTMAIN=(%RANDOM%*%CSVHOSTMAIN%/32768)+1
SET URLLISTVAULETRAP6=
SET REFERERVAULETRAP6=
CALL :%GETREFERERS% %CSVHOSTMAIN% URLLISTVAULETRAP6 REFERERVAULETRAP6 || CALL :DATASOURCEINCORRECT %GETREFHOSTS% %CSVHOSTMAIN% %URLLISTVAULETRAP6% %REFERERVAULETRAP6%
:REFERERVAULETRAP7
CALL :GETREFHOSTS 353
FOR /F %%F IN ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Load.csv" ^| FIND /C "://"') DO SET /A CSVHOSTLOAD=%%F
FOR /F %%F IN ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Main.csv" ^| FIND /C ","') DO SET /A CSVHOSTMAIN=%%F
IF %CSVHOSTLOAD% LEQ 14 CALL :DATASOURCENOTENOUGH %GETREFHOSTS% %CSVHOSTLOAD% Refer
IF %CSVHOSTMAIN% LEQ 99 CALL :DATASOURCENOTENOUGH %GETREFHOSTS% %CSVHOSTMAIN% Lists
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF %REFERERRANDOM% GEQ 11 SET "GETREFERERS=GETREFERERSLOAD"
IF %REFERERRANDOM% LEQ 10 SET "GETREFERERS=GETREFERERSMAIN"
SET /A CSVHOSTLOAD=(%RANDOM%*%CSVHOSTLOAD%/32768)+1
SET /A CSVHOSTMAIN=(%RANDOM%*%CSVHOSTMAIN%/32768)+1
SET URLLISTVAULETRAP7=
SET REFERERVAULETRAP7=
CALL :%GETREFERERS% %CSVHOSTMAIN% URLLISTVAULETRAP7 REFERERVAULETRAP7 || CALL :DATASOURCEINCORRECT %GETREFHOSTS% %CSVHOSTMAIN% %URLLISTVAULETRAP7% %REFERERVAULETRAP7%
:REFERERVAULETRAP8
CALL :GETREFHOSTS 354
FOR /F %%F IN ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Load.csv" ^| FIND /C "://"') DO SET /A CSVHOSTLOAD=%%F
FOR /F %%F IN ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Main.csv" ^| FIND /C ","') DO SET /A CSVHOSTMAIN=%%F
IF %CSVHOSTLOAD% LEQ 14 CALL :DATASOURCENOTENOUGH %GETREFHOSTS% %CSVHOSTLOAD% Refer
IF %CSVHOSTMAIN% LEQ 99 CALL :DATASOURCENOTENOUGH %GETREFHOSTS% %CSVHOSTMAIN% Lists
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF %REFERERRANDOM% GEQ 11 SET "GETREFERERS=GETREFERERSLOAD"
IF %REFERERRANDOM% LEQ 10 SET "GETREFERERS=GETREFERERSMAIN"
SET /A CSVHOSTLOAD=(%RANDOM%*%CSVHOSTLOAD%/32768)+1
SET /A CSVHOSTMAIN=(%RANDOM%*%CSVHOSTMAIN%/32768)+1
SET URLLISTVAULETRAP8=
SET REFERERVAULETRAP8=
CALL :%GETREFERERS% %CSVHOSTMAIN% URLLISTVAULETRAP8 REFERERVAULETRAP8 || CALL :DATASOURCEINCORRECT %GETREFHOSTS% %CSVHOSTMAIN% %URLLISTVAULETRAP8% %REFERERVAULETRAP8%
:REFERERVAULEreCA1
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEreCA1="http://www.gbaromsworld.blogspot.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEreCA1="http://www.digitalmaza.net"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEreCA1="http://www.digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEreCA1="http://www.digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEreCA1=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEreCA1=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEreCA1="http://gbaromsworld.blogspot.com"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEreCA1="http://digitalmaza.net"
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEreCA1="http://digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEreCA1="http://digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEreCA1=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%" GEQ "12" SET REFERERVAULEreCA1=%REFERERVAULEDEFAULT%%
:REFERERVAULEreCA2
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEreCA2="http://www.gbaromsworld.blogspot.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEreCA2="http://www.digitalmaza.net"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEreCA2="http://www.digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEreCA2="http://www.digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEreCA2=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEreCA2=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEreCA2="http://gbaromsworld.blogspot.com"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEreCA2="http://digitalmaza.net"
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEreCA2="http://digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEreCA2="http://digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEreCA2=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%" GEQ "12" SET REFERERVAULEreCA2=%REFERERVAULEDEFAULT%
:REFERERVAULEreCA3
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEreCA3="http://www.gbaromsworld.blogspot.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEreCA3="http://www.digitalmaza.net"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEreCA3="http://www.digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEreCA3="http://www.digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEreCA3=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEreCA3=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEreCA3="http://gbaromsworld.blogspot.com"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEreCA3="http://digitalmaza.net"
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEreCA3="http://digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEreCA3="http://digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEreCA3=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%" GEQ "12" SET REFERERVAULEreCA3=%REFERERVAULEDEFAULT%
:REFERERVAULEreCA4
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEreCA4="http://www.gbaromsworld.blogspot.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEreCA4="http://www.digitalmaza.net"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEreCA4="http://www.digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEreCA4="http://www.digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEreCA4=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEreCA4=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEreCA4="http://gbaromsworld.blogspot.com"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEreCA4="http://digitalmaza.net"
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEreCA4="http://digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEreCA4="http://digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEreCA4=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%" GEQ "12" SET REFERERVAULEreCA4=%REFERERVAULEDEFAULT%
:REFERERVAULEreCA5
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEreCA5="http://www.gbaromsworld.blogspot.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEreCA5="http://www.digitalmaza.net"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEreCA5="http://www.digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEreCA5="http://www.digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEreCA5=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEreCA5=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEreCA5="http://gbaromsworld.blogspot.com"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEreCA5="http://digitalmaza.net"
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEreCA5="http://digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEreCA5="http://digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEreCA5=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%" GEQ "12" SET REFERERVAULEreCA5=%REFERERVAULEDEFAULT%
:REFERERVAULEreCA6
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEreCA6="http://www.gbaromsworld.blogspot.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEreCA6="http://www.digitalmaza.net"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEreCA6="http://www.digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEreCA6="http://www.digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEreCA6=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEreCA6=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEreCA6="http://gbaromsworld.blogspot.com"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEreCA6="http://digitalmaza.net"
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEreCA6="http://digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEreCA6="http://digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEreCA6=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%" GEQ "12" SET REFERERVAULEreCA6=%REFERERVAULEDEFAULT%
:REFERERVAULEreCA7
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEreCA7="http://www.gbaromsworld.blogspot.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEreCA7="http://www.digitalmaza.net"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEreCA7="http://www.digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEreCA7="http://www.digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEreCA7=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEreCA7=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEreCA7="http://gbaromsworld.blogspot.com"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEreCA7="http://digitalmaza.net"
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEreCA7="http://digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEreCA7="http://digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEreCA7=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%" GEQ "12" SET REFERERVAULEreCA7=%REFERERVAULEDEFAULT%
:REFERERVAULEreCA8
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEreCA8="http://www.gbaromsworld.blogspot.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEreCA8="http://www.digitalmaza.net"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEreCA8="http://www.digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEreCA8="http://www.digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEreCA8=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEreCA8=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEreCA8="http://gbaromsworld.blogspot.com"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEreCA8="http://digitalmaza.net"
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEreCA8="http://digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEreCA8="http://digitalmaza.net/threads/all-gba-roms.27256"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEreCA8=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%" GEQ "12" SET REFERERVAULEreCA8=%REFERERVAULEDEFAULT%
:REFERERVAULEVIEW01
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEVIEW01="http://gallery-dump.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEVIEW01="http://gallery-dump.com/forum/viewtopic.php?t=364127"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEVIEW01="http://www.gallery-dump.com/forum/viewtopic.php?t=364127"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEVIEW01=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEVIEW01="http://gallery-dump.net"
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEVIEW01="http://gallery-dump.net/hentai/62843/gallery.html"
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEVIEW01="http://www.gallery-dump.net/hentai/62843/gallery.html"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEVIEW01=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEVIEW01="http://gallery-dump.info"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEVIEW01="http://gallery-dump.info/hentai/373798/images.html"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEVIEW01="http://www.gallery-dump.info/hentai/373798/images.html"
IF "%REFERERRANDOM%" GEQ "12" SET REFERERVAULEVIEW01=%REFERERVAULEHENTAI%
:REFERERVAULEVIEW02
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEVIEW02="http://gallery-dump.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEVIEW02="http://gallery-dump.com/forum/viewtopic.php?t=360233"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEVIEW02="http://www.gallery-dump.com/forum/viewtopic.php?t=360233"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEVIEW02=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEVIEW02="http://gallery-dump.net"
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEVIEW02="http://gallery-dump.net/hentai/47666/gallery.html"
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEVIEW02="http://www.gallery-dump.net/hentai/47666/gallery.html"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEVIEW02=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEVIEW02="http://gallery-dump.info"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEVIEW02="http://gallery-dump.info/hentai/351687/images.html"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEVIEW02="http://www.gallery-dump.info/hentai/351687/images.html"
IF "%REFERERRANDOM%" GEQ "12" SET REFERERVAULEVIEW02=%REFERERVAULEHENTAI%
:REFERERVAULEVIEW03
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEVIEW03="http://gallery-dump.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEVIEW03="http://gallery-dump.com/forum/viewtopic.php?t=360015"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEVIEW03="http://www.gallery-dump.com/forum/viewtopic.php?t=360015"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEVIEW03=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEVIEW03="http://gallery-dump.net"
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEVIEW03="http://gallery-dump.net/hentai/49876/gallery.html"
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEVIEW03="http://www.gallery-dump.net/hentai/49876/gallery.html"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEVIEW03=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEVIEW03="http://gallery-dump.info"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEVIEW03="http://gallery-dump.info/hentai/356372/images.html"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEVIEW03="http://www.gallery-dump.info/hentai/356372/images.html"
IF "%REFERERRANDOM%" GEQ "12" SET REFERERVAULEVIEW03=%REFERERVAULEHENTAI%
:REFERERVAULEVIEW04
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEVIEW04="http://gallery-dump.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEVIEW04="http://gallery-dump.com/forum/viewtopic.php?t=359354"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEVIEW04="http://www.gallery-dump.com/forum/viewtopic.php?t=359354"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEVIEW04=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEVIEW04="http://gallery-dump.net"
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEVIEW04="http://gallery-dump.net/hentai/56431/gallery.html"
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEVIEW04="http://www.gallery-dump.net/hentai/56431/gallery.html"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEVIEW04=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEVIEW04="http://gallery-dump.info"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEVIEW04="http://gallery-dump.info/hentai/351691/images.html"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEVIEW04="http://www.gallery-dump.info/hentai/351691/images.html"
IF "%REFERERRANDOM%" GEQ "12" SET REFERERVAULEVIEW04=%REFERERVAULEHENTAI%
:REFERERVAULEVIEW05
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEVIEW05="http://gallery-dump.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEVIEW05="http://gallery-dump.com/forum/viewtopic.php?t=362304"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEVIEW05="http://www.gallery-dump.com/forum/viewtopic.php?t=362304"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEVIEW05=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEVIEW05="http://gallery-dump.net"
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEVIEW05="http://gallery-dump.net/hentai/56256/gallery.html"
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEVIEW05="http://www.gallery-dump.net/hentai/56256/gallery.html"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEVIEW05=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEVIEW05= "http://gallery-dump.info"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEVIEW05="http://gallery-dump.info/hentai/366546/images.html"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEVIEW05="http://www.gallery-dump.info/hentai/366546/images.html"
IF "%REFERERRANDOM%" GEQ "12" SET REFERERVAULEVIEW05=%REFERERVAULEHENTAI%
:REFERERVAULEVIEW06
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEVIEW06="http://gallery-dump.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEVIEW06="http://gallery-dump.com/forum/viewtopic.php?t=363060"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEVIEW06="http://www.gallery-dump.com/forum/viewtopic.php?t=363060"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEVIEW06=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEVIEW06="http://gallery-dump.net"
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEVIEW06="http://gallery-dump.net/hentai/57993/gallery.html"
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEVIEW06="http://www.gallery-dump.net/hentai/57993/gallery.html"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEVIEW06=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEVIEW06="http://www.gallery-dump.info"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEVIEW06="http://gallery-dump.info/hentai/368278/images.html"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEVIEW06="http://www.gallery-dump.info/hentai/368278/images.html"
IF "%REFERERRANDOM%" GEQ "12" SET REFERERVAULEVIEW06=%REFERERVAULEHENTAI%
:REFERERVAULEVIEW07
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEVIEW07="http://gallery-dump.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEVIEW07="http://gallery-dump.com/forum/viewtopic.php?t=363057"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEVIEW07="http://www.gallery-dump.com/forum/viewtopic.php?t=363057"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEVIEW07=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEVIEW07="http://gallery-dump.net"
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEVIEW07="http://.gallery-dump.net/hentai/57989/gallery.html"
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEVIEW07="http://www.gallery-dump.net/hentai/57989/gallery.html"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEVIEW07=%REFERERVAULEHENTAI%
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEVIEW07="http://gallery-dump.info"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEVIEW07="http://gallery-dump.info/hentai/368274/images.html"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEVIEW07="http://www.gallery-dump.info/hentai/368274/images.html"
IF "%REFERERRANDOM%" GEQ "12" SET REFERERVAULEVIEW07=%REFERERVAULEHENTAI%
:REFERERVAULEVIEW08
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEVIEW08="http://gallery-dump.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEVIEW08="http://gallery-dump.com/forum/viewtopic.php?t=363059"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEVIEW08="http://www.gallery-dump.com/forum/viewtopic.php?t=363059"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEVIEW08=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEVIEW08="http://gallery-dump.net"
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEVIEW08="http://gallery-dump.net/hentai/57992/gallery.html"
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEVIEW08="http://www.gallery-dump.net/hentai/57992/gallery.html"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEVIEW08=%REFERERVAULEHENTAI%
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEVIEW08="http://gallery-dump.info"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEVIEW08="http://gallery-dump.info/hentai/368277/images.html"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEVIEW08="http://www.gallery-dump.info/hentai/368277/images.html"
IF "%REFERERRANDOM%" GEQ "12" SET REFERERVAULEVIEW08=%REFERERVAULEHENTAI%
:REFERERVAULEVIEW09
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEVIEW09="http://gallery-dump.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEVIEW09="http://gallery-dump.com/forum/viewtopic.php?t=364131"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEVIEW09="http://www.gallery-dump.com/forum/viewtopic.php?t=364131"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEVIEW09=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEVIEW09="http://gallery-dump.net"
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEVIEW09="http://gallery-dump.net/hentai/62845/gallery.html"
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEVIEW09="http://www.gallery-dump.net/hentai/62845/gallery.html"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEVIEW09=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEVIEW09="http://gallery-dump.info"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEVIEW09="http://gallery-dump.info/hentai/373802/images.html"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEVIEW09="http://www.gallery-dump.info/hentai/373802/images.html"
IF "%REFERERRANDOM%"=="12" SET REFERERVAULEVIEW09=%REFERERVAULEHENTAI%
IF "%REFERERRANDOM%"=="13" SET REFERERVAULEVIEW09=%REFERERVAULEHENTAI%
IF "%REFERERRANDOM%"=="14" SET REFERERVAULEVIEW09=%REFERERVAULEHENTAI%
IF "%REFERERRANDOM%"=="15" SET REFERERVAULEVIEW09=%REFERERVAULEHENTAI%
:REFERERVAULEVIEW010
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEVIEW010="http://gallery-dump.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEVIEW010="http://gallery-dump.com/forum/viewtopic.php?t=364448"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEVIEW010="http://www.gallery-dump.com/forum/viewtopic.php?t=364448"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEVIEW010=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEVIEW010="http://gallery-dump.net"
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEVIEW010="http://gallery-dump.net/hentai/64190/gallery.html"
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEVIEW010="http://www.gallery-dump.net/hentai/64190/gallery.html"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEVIEW010=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEVIEW010="http://gallery-dump.info"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEVIEW10="http://gallery-dump.info/hentai/375360/images.html"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEVIEW10="http://www.gallery-dump.info/hentai/375360/images.html"
IF "%REFERERRANDOM%" GEQ "12" SET REFERERVAULEVIEW10=%REFERERVAULEHENTAI%
:REFERERVAULEVIEW011
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEVIEW011="http://gallery-dump.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEVIEW011="http://gallery-dump.com/forum/viewtopic.php?t=364132"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEVIEW011="http://www.gallery-dump.com/forum/viewtopic.php?t=364132"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEVIEW011=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEVIEW011="http://gallery-dump.net"
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEVIEW011="http://gallery-dump.net/hentai/62847/gallery.html"
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEVIEW011="http://www.gallery-dump.net/hentai/62847/gallery.html"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEVIEW011=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEVIEW011="http://gallery-dump.info"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEVIEW11="http://gallery-dump.info/hentai/373805/images.html"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEVIEW11="http://www.gallery-dump.info/hentai/373805/images.html"
IF "%REFERERRANDOM%" GEQ "12" SET REFERERVAULEVIEW11=%REFERERVAULEHENTAI%
:REFERERVAULEVIEW012
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEVIEW012="http://gallery-dump.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEVIEW012="http://gallery-dump.com/forum/viewtopic.php?t=362693"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEVIEW012="http://www.gallery-dump.com/forum/viewtopic.php?t=362693"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEVIEW012=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEVIEW012="http://gallery-dump.net"
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEVIEW012="http://gallery-dump.net/hentai/57187/gallery.html"
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEVIEW012="http://www.gallery-dump.net/hentai/57187/gallery.html"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEVIEW012=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEVIEW012="http://gallery-dump.info"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEVIEW12="http://gallery-dump.info/hentai/367318/images.html"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEVIEW12="http://www.gallery-dump.info/hentai/367318/images.html"
IF "%REFERERRANDOM%" GEQ "12" SET REFERERVAULEVIEW12=%REFERERVAULEHENTAI%
:REFERERVAULEVIEW013
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEVIEW013="http://gallery-dump.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEVIEW013="http://gallery-dump.com/forum/viewtopic.php?t=362694"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEVIEW013="http://www.gallery-dump.com/forum/viewtopic.php?t=362694"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEVIEW013=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEVIEW013="http://gallery-dump.net"
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEVIEW013="http://gallery-dump.net"
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEVIEW013="http://www.gallery-dump.net"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEVIEW013=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEVIEW013= "http://gallery-dump.info"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEVIEW13="http://gallery-dump.info"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEVIEW13="http://www.gallery-dump.info"
IF "%REFERERRANDOM%" GEQ "12" SET REFERERVAULEVIEW13=%REFERERVAULEHENTAI%
:REFERERVAULEVIEW014
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEVIEW014="http://gallery-dump.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEVIEW014="http://gallery-dump.com/forum/viewtopic.php?t=364133"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEVIEW014="http://www.gallery-dump.com/forum/viewtopic.php?t=364133"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEVIEW014=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEVIEW014="http://gallery-dump.net"
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEVIEW014="http://gallery-dump.net/hentai/62848/gallery.html"
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEVIEW014="http://www.gallery-dump.net/hentai/62848/gallery.html"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEVIEW014=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEVIEW014="http://www.gallery-dump.info"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEVIEW14="http://gallery-dump.info/hentai/373806/images.html"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEVIEW14="http://www.gallery-dump.info/hentai/373806/images.html"
IF "%REFERERRANDOM%" GEQ "12" SET REFERERVAULEVIEW14=%REFERERVAULEHENTAI%
:REFERERVAULEVIEW015
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEVIEW015="http://gallery-dump.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEVIEW015="http://gallery-dump.com/forum/viewtopic.php?t=362696"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEVIEW015="http://www.gallery-dump.com/forum/viewtopic.php?t=362696"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEVIEW015=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEVIEW015="http://gallery-dump.net"
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEVIEW015="http://.gallery-dump.net/hentai/57190/gallery.html"
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEVIEW015="http://www.gallery-dump.net/hentai/57190/gallery.html"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEVIEW015=%REFERERVAULEHENTAI%
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEVIEW015="http://gallery-dump.info"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEVIEW15="http://gallery-dump.info/hentai/367320/images.html"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEVIEW15="http://www.gallery-dump.info/hentai/367320/images.html"
IF "%REFERERRANDOM%" GEQ "12" SET REFERERVAULEVIEW15=%REFERERVAULEHENTAI%
:REFERERVAULEVIEW016
SET /A REFERERRANDOM=%RANDOM% %%15 +1
IF "%REFERERRANDOM%"=="1" SET REFERERVAULEVIEW016="http://gallery-dump.com"
IF "%REFERERRANDOM%"=="2" SET REFERERVAULEVIEW016="http://gallery-dump.com/forum/viewtopic.php?t=362697"
IF "%REFERERRANDOM%"=="3" SET REFERERVAULEVIEW016="http://www.gallery-dump.com/forum/viewtopic.php?t=362697"
IF "%REFERERRANDOM%"=="4" SET REFERERVAULEVIEW016=%REFERERVAULEDEFAULT%
IF "%REFERERRANDOM%"=="5" SET REFERERVAULEVIEW016="http://gallery-dump.net"
IF "%REFERERRANDOM%"=="6" SET REFERERVAULEVIEW016="http://gallery-dump.net/hentai/57191/gallery.html"
IF "%REFERERRANDOM%"=="7" SET REFERERVAULEVIEW016="http://www.gallery-dump.net/hentai/57191/gallery.html"
IF "%REFERERRANDOM%"=="8" SET REFERERVAULEVIEW016=%REFERERVAULEHENTAI%
IF "%REFERERRANDOM%"=="9" SET REFERERVAULEVIEW016="http://gallery-dump.info"
IF "%REFERERRANDOM%"=="10" SET REFERERVAULEVIEW16="http://gallery-dump.info/hentai/367321/images.html"
IF "%REFERERRANDOM%"=="11" SET REFERERVAULEVIEW16="http://www.gallery-dump.info/hentai/367321/images.html"
IF "%REFERERRANDOM%" GEQ "12" SET REFERERVAULEVIEW16=%REFERERVAULEHENTAI%
ECHO.
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO. []                                                    []
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO. []                                                    []
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO.
DEL /Q ".\ff\Data\profile_normal\user.jsrename"
DEL /Q ".\ff\Data\profile_piracy\user.jsrename"
COPY /Y "Z:\Database\ff\user.js" ".\ff\Data\profile_normal\user.js"
COPY /Y "Z:\Database\ff\user.js" ".\ff\Data\profile_piracy\user.js"
FOR /F "tokens=*" %%F in ('FINDSTR /R /N "^" ".\ff\Data\profile_normal\user.js" ^| FIND /C ":"') DO SET EMPTYNORMAL=%%F
IF %EMPTYNORMAL% LSS 1 TIMEOUT 2 /NOBREAK && GOTO USERJS
FOR /F "tokens=*" %%F in ('FINDSTR /R /N "^" ".\ff\Data\profile_piracy\user.js" ^| FIND /C ":"') DO SET EMPTYPIRACY=%%F
IF %EMPTYPIRACY% LSS 1 TIMEOUT 2 /NOBREAK && GOTO USERJS
type ".\ff\Data\profile_normal\user.js" | findrepl "IMACROMODE" "%IMACRONORMAL%" > ".\ff\Data\profile_normal\user.jsrename"
type ".\ff\Data\profile_piracy\user.js" | findrepl "IMACROMODE" "%IMACROPIRACY%" > ".\ff\Data\profile_piracy\user.jsrename"
DEL /Q ".\ff\Data\profile_normal\user.js"
DEL /Q ".\ff\Data\profile_piracy\user.js"
REN ".\ff\Data\profile_normal\user.jsrename" user.js
REN ".\ff\Data\profile_piracy\user.jsrename" user.js
type ".\ff\Data\profile_normal\user.js" | findrepl "profileMode|agentSpoofvaule|browserCacheDiskEnable|browserCacheMemoryCapacity" /A "profile_normal|false|%browserCacheDiskEnable%|%browserCacheMemoryCapacity%" > ".\ff\Data\profile_normal\user.jsrename"
type ".\ff\Data\profile_piracy\user.js" | findrepl "profileMode|agentSpoofvaule|browserCacheDiskEnable|browserCacheMemoryCapacity" /A "profile_piracy|false|%browserCacheDiskEnable%|%browserCacheMemoryCapacity%" > ".\ff\Data\profile_piracy\user.jsrename"
DEL /Q ".\ff\Data\profile_normal\user.js"
DEL /Q ".\ff\Data\profile_piracy\user.js"
REN ".\ff\Data\profile_normal\user.jsrename" user.js
REN ".\ff\Data\profile_piracy\user.jsrename" user.js
type ".\ff\Data\profile_normal\user.js" | findrepl "http://google.ws|http://google.vu|http://google.us|http://google.sh" /A "%REFERERVAULEMULT1%|%REFERERVAULEMULT2%|%REFERERVAULEMULT3%|%REFERERVAULEMULT4%" > ".\ff\Data\profile_normal\user.jsrename"
type ".\ff\Data\profile_piracy\user.js" | findrepl "http://google.ws|http://google.vu|http://google.us|http://google.sh" /A "%REFERERVAULEMULT1%|%REFERERVAULEMULT2%|%REFERERVAULEMULT3%|%REFERERVAULEMULT4%" > ".\ff\Data\profile_piracy\user.jsrename"
DEL /Q ".\ff\Data\profile_normal\user.js"
DEL /Q ".\ff\Data\profile_piracy\user.js"
REN ".\ff\Data\profile_normal\user.jsrename" user.js
REN ".\ff\Data\profile_piracy\user.jsrename" user.js
type ".\ff\Data\profile_normal\user.js" | findrepl "http://google.fr|http://google.gf|http://google.gl|http://google.is" /A "%REFERERVAULETRAP1%|%REFERERVAULETRAP2%|%REFERERVAULETRAP3%|%REFERERVAULETRAP4%" > ".\ff\Data\profile_normal\user.jsrename"
type ".\ff\Data\profile_piracy\user.js" | findrepl "http://google.fr|http://google.gf|http://google.gl|http://google.is" /A "%REFERERVAULETRAP1%|%REFERERVAULETRAP2%|%REFERERVAULETRAP3%|%REFERERVAULETRAP4%" > ".\ff\Data\profile_piracy\user.jsrename"
DEL /Q ".\ff\Data\profile_normal\user.js"
DEL /Q ".\ff\Data\profile_piracy\user.js"
REN ".\ff\Data\profile_normal\user.jsrename" user.js
REN ".\ff\Data\profile_piracy\user.jsrename" user.js
type ".\ff\Data\profile_normal\user.js" | findrepl "http://google.hu|http://google.ae|http://google.at|http://google.tt" /A "%REFERERVAULETRAP5%|%REFERERVAULETRAP6%|%REFERERVAULETRAP7%|%REFERERVAULETRAP8%" > ".\ff\Data\profile_normal\user.jsrename"
type ".\ff\Data\profile_piracy\user.js" | findrepl "http://google.hu|http://google.ae|http://google.at|http://google.tt" /A "%REFERERVAULETRAP5%|%REFERERVAULETRAP6%|%REFERERVAULETRAP7%|%REFERERVAULETRAP8%" > ".\ff\Data\profile_piracy\user.jsrename"
DEL /Q ".\ff\Data\profile_normal\user.js"
DEL /Q ".\ff\Data\profile_piracy\user.js"
REN ".\ff\Data\profile_normal\user.jsrename" user.js
REN ".\ff\Data\profile_piracy\user.jsrename" user.js
type ".\ff\Data\profile_normal\user.js" | findrepl "http://google.com.af|http://google.com.au|http://google.com.hk|http://google.com.do" /A "%REFERERVAULEreCA1%|%REFERERVAULEreCA2%|%REFERERVAULEreCA3%|%REFERERVAULEreCA4%" > ".\ff\Data\profile_normal\user.jsrename"
type ".\ff\Data\profile_piracy\user.js" | findrepl "http://google.com.af|http://google.com.au|http://google.com.hk|http://google.com.do" /A "%REFERERVAULEreCA1%|%REFERERVAULEreCA2%|%REFERERVAULEreCA3%|%REFERERVAULEreCA4%" > ".\ff\Data\profile_piracy\user.jsrename"
DEL /Q ".\ff\Data\profile_normal\user.js"
DEL /Q ".\ff\Data\profile_piracy\user.js"
REN ".\ff\Data\profile_normal\user.jsrename" user.js
REN ".\ff\Data\profile_piracy\user.jsrename" user.js
type ".\ff\Data\profile_normal\user.js" | findrepl "http://google.com.co|http://google.com.ag|http://google.com.kh|http://google.com.br" /A "%REFERERVAULEreCA5%|%REFERERVAULEreCA6%|%REFERERVAULEreCA7%|%REFERERVAULEreCA8%" > ".\ff\Data\profile_normal\user.jsrename"
type ".\ff\Data\profile_piracy\user.js" | findrepl "http://google.com.co|http://google.com.ag|http://google.com.kh|http://google.com.br" /A "%REFERERVAULEreCA5%|%REFERERVAULEreCA6%|%REFERERVAULEreCA7%|%REFERERVAULEreCA8%" > ".\ff\Data\profile_piracy\user.jsrename"
DEL /Q ".\ff\Data\profile_normal\user.js"
DEL /Q ".\ff\Data\profile_piracy\user.js"
REN ".\ff\Data\profile_normal\user.jsrename" user.js
REN ".\ff\Data\profile_piracy\user.jsrename" user.js
type ".\ff\Data\profile_normal\user.js" | findrepl "http://image.google.co.uz|http://image.google.co.ug|http://image.google.co.kr|http://image.google.co.jp" /A "%REFERERVAULEVIEW01%|%REFERERVAULEVIEW02%|%REFERERVAULEVIEW03%|%REFERERVAULEVIEW04%%" > ".\ff\Data\profile_normal\user.jsrename"
type ".\ff\Data\profile_piracy\user.js" | findrepl "http://image.google.co.uz|http://image.google.co.ug|http://image.google.co.kr|http://image.google.co.jp" /A "%REFERERVAULEVIEW01%|%REFERERVAULEVIEW02%|%REFERERVAULEVIEW03%|%REFERERVAULEVIEW04%%" > ".\ff\Data\profile_piracy\user.jsrename"
DEL /Q ".\ff\Data\profile_normal\user.js"
DEL /Q ".\ff\Data\profile_piracy\user.js"
REN ".\ff\Data\profile_normal\user.jsrename" user.js
REN ".\ff\Data\profile_piracy\user.jsrename" user.js
type ".\ff\Data\profile_normal\user.js" | findrepl "http://image.google.co.ke|http://image.google.co.ma|http://image.google.co.mz|http://image.google.co.nz" /A "%REFERERVAULEVIEW05%|%REFERERVAULEVIEW06%|%REFERERVAULEVIEW07%|%REFERERVAULEVIEW08%" > ".\ff\Data\profile_normal\user.jsrename"
type ".\ff\Data\profile_piracy\user.js" | findrepl "http://image.google.co.ke|http://image.google.co.ma|http://image.google.co.mz|http://image.google.co.nz" /A "%REFERERVAULEVIEW05%|%REFERERVAULEVIEW06%|%REFERERVAULEVIEW07%|%REFERERVAULEVIEW08%" > ".\ff\Data\profile_piracy\user.jsrename"
DEL /Q ".\ff\Data\profile_normal\user.js"
DEL /Q ".\ff\Data\profile_piracy\user.js"
REN ".\ff\Data\profile_normal\user.jsrename" user.js
REN ".\ff\Data\profile_piracy\user.jsrename" user.js
type ".\ff\Data\profile_normal\user.js" | findrepl "http://image.google.co.vi|http://image.google.co.ls|http://image.google.co.za|http://image.google.co.zm" /A "%REFERERVAULEVIEW09%|%REFERERVAULEVIEW10%|%REFERERVAULEVIEW11%|%REFERERVAULEVIEW12%%" > ".\ff\Data\profile_normal\user.jsrename"
type ".\ff\Data\profile_piracy\user.js" | findrepl "http://image.google.co.vi|http://image.google.co.ls|http://image.google.co.za|http://image.google.co.zm" /A "%REFERERVAULEVIEW09%|%REFERERVAULEVIEW10%|%REFERERVAULEVIEW11%|%REFERERVAULEVIEW12%%" > ".\ff\Data\profile_piracy\user.jsrename"
DEL /Q ".\ff\Data\profile_normal\user.js"
DEL /Q ".\ff\Data\profile_piracy\user.js"
REN ".\ff\Data\profile_normal\user.jsrename" user.js
REN ".\ff\Data\profile_piracy\user.jsrename" user.js
type ".\ff\Data\profile_normal\user.js" | findrepl "http://image.google.co.zw|http://image.google.co.tz|http://image.google.co.ve|http://image.google.co.ao" /A "%REFERERVAULEVIEW13%|%REFERERVAULEVIEW14%|%REFERERVAULEVIEW15%|%REFERERVAULEVIEW16%" > ".\ff\Data\profile_normal\user.jsrename"
type ".\ff\Data\profile_piracy\user.js" | findrepl "http://image.google.co.zw|http://image.google.co.tz|http://image.google.co.ve|http://image.google.co.ao" /A "%REFERERVAULEVIEW13%|%REFERERVAULEVIEW14%|%REFERERVAULEVIEW15%|%REFERERVAULEVIEW16%" > ".\ff\Data\profile_piracy\user.jsrename"
DEL /Q ".\ff\Data\profile_normal\user.js"
DEL /Q ".\ff\Data\profile_piracy\user.js"
REN ".\ff\Data\profile_normal\user.jsrename" user.js
REN ".\ff\Data\profile_piracy\user.jsrename" user.js
type ".\ff\Data\profile_normal\user.js" | findrepl "http://google.co.th|http://hotmail.com|http://google.co.uk" /A "%REFERERVAULEDEFAULT%|%REFERERVAULEEMAIL%|%REFERERVAULEHENTAI%" > ".\ff\Data\profile_normal\user.jsrename"
type ".\ff\Data\profile_piracy\user.js" | findrepl "http://google.co.th|http://hotmail.com|http://google.co.uk" /A "%REFERERVAULEDEFAULT%|%REFERERVAULEEMAIL%|%REFERERVAULEHENTAI%" > ".\ff\Data\profile_piracy\user.jsrename"
DEL /Q ".\ff\Data\profile_normal\user.js"
DEL /Q ".\ff\Data\profile_piracy\user.js"
REN ".\ff\Data\profile_normal\user.jsrename" user.js
REN ".\ff\Data\profile_piracy\user.jsrename" user.js
type ".\ff\Data\profile_normal\user.js" | findrepl "http://search.google.com" "%REFERERVAULEDEFAULT%" > ".\ff\Data\profile_normal\user.jsrename"
type ".\ff\Data\profile_piracy\user.js" | findrepl "http://search.google.com" "%REFERERVAULEDEFAULT%" > ".\ff\Data\profile_piracy\user.jsrename"
DEL /Q ".\ff\Data\profile_normal\user.js"
DEL /Q ".\ff\Data\profile_piracy\user.js"
REN ".\ff\Data\profile_normal\user.jsrename" user.js
REN ".\ff\Data\profile_piracy\user.jsrename" user.js
type "%USERPROFILE%\Documents\iMacros\Macros\Ads_Skip_Bot_-_NoReCaptcha.iim" | findrepl "URLLISTVAULEMULT1|URLLISTVAULEMULT2|URLLISTVAULEMULT3|URLLISTVAULEMULT4" /A "%URLLISTVAULEMULT1%|%URLLISTVAULEMULT2%|%URLLISTVAULEMULT3%|%URLLISTVAULEMULT4%" > "%USERPROFILE%\Documents\iMacros\Macros\Ads_Skip_Bot_-_NoReCaptcha.iimrename"
DEL /Q "%USERPROFILE%\Documents\iMacros\Macros\Ads_Skip_Bot_-_NoReCaptcha.iim"
REN "%USERPROFILE%\Documents\iMacros\Macros\Ads_Skip_Bot_-_NoReCaptcha.iimrename" Ads_Skip_Bot_-_NoReCaptcha.iim
type "%USERPROFILE%\Documents\iMacros\Macros\Ads_Skip_Bot_-_NoReCaptcha.iim" | findrepl "URLLISTVAULETRAP1|URLLISTVAULETRAP2|URLLISTVAULETRAP3|URLLISTVAULETRAP4" /A "%URLLISTVAULETRAP1%|%URLLISTVAULETRAP2%|%URLLISTVAULETRAP3%|%URLLISTVAULETRAP4%" > "%USERPROFILE%\Documents\iMacros\Macros\Ads_Skip_Bot_-_NoReCaptcha.iimrename"
DEL /Q "%USERPROFILE%\Documents\iMacros\Macros\Ads_Skip_Bot_-_NoReCaptcha.iim"
REN "%USERPROFILE%\Documents\iMacros\Macros\Ads_Skip_Bot_-_NoReCaptcha.iimrename" Ads_Skip_Bot_-_NoReCaptcha.iim
type "%USERPROFILE%\Documents\iMacros\Macros\Ads_Skip_Bot_-_NoReCaptcha.iim" | findrepl "URLLISTVAULETRAP5|URLLISTVAULETRAP6|URLLISTVAULETRAP7|URLLISTVAULETRAP8" /A "%URLLISTVAULETRAP5%|%URLLISTVAULETRAP6%|%URLLISTVAULETRAP7%|%URLLISTVAULETRAP8%" > "%USERPROFILE%\Documents\iMacros\Macros\Ads_Skip_Bot_-_NoReCaptcha.iimrename"
DEL /Q "%USERPROFILE%\Documents\iMacros\Macros\Ads_Skip_Bot_-_NoReCaptcha.iim"
REN "%USERPROFILE%\Documents\iMacros\Macros\Ads_Skip_Bot_-_NoReCaptcha.iimrename" Ads_Skip_Bot_-_NoReCaptcha.iim
TIMEOUT 1 /NOBREAK
FOR /F "tokens=*" %%F in ('FINDSTR /R /N "^" ".\ff\Data\profile_normal\user.js" ^| FIND /C ":"') DO SET EMPTYNORMAL=%%F
IF %EMPTYNORMAL% LSS 1 TIMEOUT 2 /NOBREAK && GOTO USERJS
FOR /F "tokens=*" %%F in ('FINDSTR /R /N "^" ".\ff\Data\profile_piracy\user.js" ^| FIND /C ":"') DO SET EMPTYPIRACY=%%F
IF %EMPTYPIRACY% LSS 1 TIMEOUT 2 /NOBREAK && GOTO USERJS
ECHO. 
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO. []                                                    []
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO. []                                                    []
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO.
REM \\ type ".\ff\Data\profile_normal\compatibility.ini" |findrepl "Safe Mode" "52.0.1_20170316213829/20170316213829" > ".\ff\Data\profile_normal\compatibility.ini"
DEL /Q ".\ff\Data\profile_normal\_CACHE_CLEAN_"
DEL /Q ".\ff\Data\profile_normal\flashgot.log.bak"
DEL /Q ".\ff\Data\profile_normal\prefs-1.js"
DEL /Q ".\ff\Data\profile_normal\prefs-2.js"
DEL /Q ".\ff\Data\profile_normal\prefs-3.js"
DEL /Q ".\ff\Data\profile_normal\prefs-4.js"
DEL /Q ".\ff\Data\profile_normal\sessionCheckpoints.json"
DEL /Q ".\ff\Data\profile_normal\localstore-safe.rdf"
DEL /Q ".\ff\Data\profile_normal\session.rdf"
DEL /Q ".\ff\Data\profile_normal\session-1.rdf"
DEL /Q ".\ff\Data\profile_normal\*.txt"
DEL /Q ".\ff\Data\profile_normal\localstore-safe.rdf"
REM \\ DEL /Q ".\ff\Data\profile_normal\places.sqlite"
REM \\ DEL /Q ".\ff\Data\profile_normal\places.sqlite.corrupt"
REM \\ DEL /Q ".\ff\Data\profile_normal\places.sqlite-shm"
REM \\ DEL /Q ".\ff\Data\profile_normal\places.sqlite-wal"
REM \\ DEL /Q ".\ff\Data\profile_normal\webappsstore.sqlite"
COPY /Y "Z:\Database\ff\adblockplus\*.CSS" ".\ff\data\profile_normal\adblockplus"
COPY /Y "Z:\Database\ff\adblockplus\*.INI" ".\ff\data\profile_normal\adblockplus"
COPY /Y "Z:\Database\ff\extension-data\*.sqlite" ".\ff\data\profile_normal\extension-data"
COPY /Y "Z:\Database\ff\normal\*.sqlite" ".\ff\data\profile_normal"
COPY /Y "Z:\Database\ff\normal\*.rdf" ".\ff\data\profile_normal"
COPY /Y "Z:\Database\ff\normal\*.json" ".\ff\data\profile_normal"
COPY /Y "Z:\Database\ff\normal\*.db" ".\ff\data\profile_normal"
COPY /Y "Z:\Database\ff\normal\*.ini" ".\ff\data\profile_normal"
IF NOT EXIST ".\ff\data\profile_normal\gm_scripts" MKDIR ".\ff\data\profile_normal\gm_scripts"
COPY /Y "Z:\Database\ff\gm_scripts\*.*" ".\ff\data\profile_normal\gm_scripts"
IF NOT EXIST ".\ff\data\profile_normal\gm_scripts\skip_bitly.com_warnning" MKDIR ".\ff\data\profile_normal\gm_scripts\skip_bitly.com_warnning"
COPY /Y "Z:\Database\ff\gm_scripts\skip_bitly.com_warnning\*" ".\ff\data\profile_normal\gm_scripts\skip_bitly.com_warnning"
IF NOT EXIST ".\ff\data\profile_normal\gm_scripts\Anti-Adblock_Killer_Reek" MKDIR ".\ff\data\profile_normal\gm_scripts\Anti-Adblock_Killer_Reek"
COPY /Y "Z:\Database\ff\gm_scripts\Anti-Adblock_Killer_Reek\*" ".\ff\data\profile_normal\gm_scripts\Anti-Adblock_Killer_Reek"
IF NOT EXIST ".\ff\data\profile_normal\gm_scripts\AllowPageClose" MKDIR ".\ff\data\profile_normal\gm_scripts\AllowPageClose"
COPY /Y "Z:\Database\ff\gm_scripts\AllowPageClose\*.*" ".\ff\data\profile_normal\gm_scripts\AllowPageClose"
IF NOT EXIST ".\ff\data\profile_normal\gm_scripts\BlockUnloadEvents" MKDIR ".\ff\data\profile_normal\gm_scripts\BlockUnloadEvents"
COPY /Y "Z:\Database\ff\gm_scripts\BlockUnloadEvents\*.*" ".\ff\data\profile_normal\gm_scripts\BlockUnloadEvents"
IF NOT EXIST ".\ff\data\profile_normal\gm_scripts\Disable_-_remove_onbeforeunload" MKDIR ".\ff\data\profile_normal\gm_scripts\Disable_-_remove_onbeforeunload"
COPY /Y "Z:\Database\ff\gm_scripts\Disable_-_remove_onbeforeunload\*" ".\ff\data\profile_normal\gm_scripts\Disable_-_remove_onbeforeunload"
IF NOT EXIST ".\ff\data\profile_normal\gm_scripts\Exit_Block_Blocker" MKDIR ".\ff\data\profile_normal\gm_scripts\Exit_Block_Blocker"
COPY /Y "Z:\Database\ff\gm_scripts\Exit_Block_Blocker\*.*" ".\ff\data\profile_normal\gm_scripts\Exit_Block_Blocker"
IF NOT EXIST ".\ff\data\profile_normal\gm_scripts\Kill_Sure_Want_To_Nav_Away" MKDIR ".\ff\data\profile_normal\gm_scripts\Kill_Sure_Want_To_Nav_Away"
COPY /Y "Z:\Database\ff\gm_scripts\Kill_Sure_Want_To_Nav_Away\*" ".\ff\data\profile\gm_scripts\Kill_Sure_Want_To_Nav_Away"
IF NOT EXIST ".\ff\data\profile_normal\gm_scripts\Linkify_Plus" MKDIR ".\ff\data\profile_normal\gm_scripts\Linkify_Plus"
COPY /Y "Z:\Database\ff\gm_scripts\Linkify_Plus\*.*" ".\ff\data\profile_normal\gm_scripts\Linkify_Plus"
IF NOT EXIST ".\ff\data\profile_normal\gm_scripts\Linkify_Plus_Redirect" MKDIR ".\ff\data\profile_normal\gm_scripts\Linkify_Plus_Redirect"
COPY /Y "Z:\Database\ff\gm_scripts\Linkify_Plus_Redirect\*.*" ".\ff\data\profile_normal\gm_scripts\Linkify_Plus_Redirect"
IF NOT EXIST ".\ff\data\profile_normal\gm_scripts\Remove_OnUnload_Test" MKDIR ".\ff\data\profile_normal\gm_scripts\Remove_OnUnload_Test"
COPY /Y "Z:\Database\ff\gm_scripts\Remove_OnUnload_Test\*.*" ".\ff\data\profile_normal\gm_scripts\Remove_OnUnload_Test"
IF NOT EXIST ".\ff\data\profile_normal\gm_scripts\TinyPaste_Or_Tny.cz_[Kaum_Ndaloe_2014]" MKDIR ".\ff\data\profile_normal\gm_scripts\TinyPaste_Or_Tny.cz_[Kaum_Ndaloe_2014]"
COPY /Y "Z:\Database\ff\gm_scripts\TinyPaste_Or_Tny.cz_[Kaum_Ndaloe_2014]\*" ".\ff\data\profile_normal\gm_scripts\TinyPaste_Or_Tny.cz_[Kaum_Ndaloe_2014]"
IF NOT EXIST ".\ff\data\profile_normal\gm_scripts\simple_html_numeric_captcha_solver" MKDIR ".\ff\data\profile_normal\gm_scripts\simple_html_numeric_captcha_solver"
COPY /Y "Z:\Database\ff\gm_scripts\simple_html_numeric_captcha_solver\*.*" ".\ff\data\profile_normal\gm_scripts\simple_html_numeric_captcha_solver"
IF NOT EXIST ".\ff\data\profile_normal\gm_scripts\reCAPTCHA_Helper" MKDIR ".\ff\data\profile_normal\gm_scripts\reCAPTCHA_Helper"
COPY /Y "Z:\Database\ff\gm_scripts\reCAPTCHA_Helper\*.*" ".\ff\data\profile_normal\gm_scripts\reCAPTCHA_Helper"
IF NOT EXIST ".\ff\data\profile_normal\gm_scripts\reCAPTCHA_Helper_input" MKDIR ".\ff\data\profile_normal\gm_scripts\reCAPTCHA_Helper_input"
COPY /Y "Z:\Database\ff\gm_scripts\reCAPTCHA_Helper_input\*.*" ".\ff\data\profile_normal\gm_scripts\reCAPTCHA_Helper_input"
IF NOT EXIST ".\ff\data\profile_normal\gm_scripts\reCAPTCHA_Helper_input_houndify" MKDIR ".\ff\data\profile_normal\gm_scripts\reCAPTCHA_Helper_input_houndify"
COPY /Y "Z:\Database\ff\gm_scripts\reCAPTCHA_Helper_input_houndify\*.*" ".\ff\data\profile_normal\gm_scripts\reCAPTCHA_Helper_input_houndify"
IF NOT EXIST ".\ff\data\profile_normal\gm_scripts\Disable_redirection" MKDIR ".\ff\data\profile_normal\gm_scripts\Disable_redirection"
COPY /Y "Z:\Database\ff\gm_scripts\Disable_redirection\*.*" ".\ff\data\profile_normal\gm_scripts\Disable_redirection"
ECHO.
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO. []                                                    []
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO. []                                                    []
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO.
REM \\ type ".\ff\Data\profile_piracy\compatibility.ini" |findrepl "Safe Mode" "52.0.1_20170316213829/20170316213829" > ".\ff\Data\profile_piracy\compatibility.ini"
DEL /Q ".\ff\Data\profile_piracy\_CACHE_CLEAN_"
DEL /Q ".\ff\Data\profile_piracy\flashgot.log.bak"
DEL /Q ".\ff\Data\profile_piracy\prefs-1.js"
DEL /Q ".\ff\Data\profile_piracy\prefs-2.js"
DEL /Q ".\ff\Data\profile_piracy\prefs-3.js"
DEL /Q ".\ff\Data\profile_piracy\prefs-4.js"
DEL /Q ".\ff\Data\profile_piracy\sessionCheckpoints.json"
DEL /Q ".\ff\Data\profile_piracy\localstore-safe.rdf"
DEL /Q ".\ff\Data\profile_piracy\session.rdf"
DEL /Q ".\ff\Data\profile_piracy\session-1.rdf"
DEL /Q ".\ff\Data\profile_piracy\*.txt"
DEL /Q ".\ff\Data\profile_piracy\localstore-safe.rdf"
REM \\ DEL /Q ".\ff\Data\profile_piracy\places.sqlite"
REM \\ DEL /Q ".\ff\Data\profile_piracy\places.sqlite.corrupt"
REM \\ DEL /Q ".\ff\Data\profile_piracy\places.sqlite-shm"
REM \\ DEL /Q ".\ff\Data\profile_piracy\places.sqlite-wal"
REM \\ DEL /Q ".\ff\Data\profile_piracy\webappsstore.sqlite"
COPY /Y "Z:\Database\ff\adblockplus\*.CSS" ".\ff\data\profile_piracy\adblockplus"
COPY /Y "Z:\Database\ff\adblockplus\*.INI" ".\ff\data\profile_piracy\adblockplus"
COPY /Y "Z:\Database\ff\extension-data\*.sqlite" ".\ff\data\profile_piracy\extension-data"
COPY /Y "Z:\Database\ff\piracy\*.sqlite" ".\ff\data\profile_piracy"
COPY /Y "Z:\Database\ff\piracy\*.rdf" ".\ff\data\profile_piracy"
COPY /Y "Z:\Database\ff\piracy\*.json" ".\ff\data\profile_piracy"
COPY /Y "Z:\Database\ff\piracy\*.db" ".\ff\data\profile_piracy"
COPY /Y "Z:\Database\ff\piracy\*.ini" ".\ff\data\profile_piracy"
IF NOT EXIST ".\ff\data\profile_piracy\gm_scripts" MKDIR ".\ff\data\profile_piracy\gm_scripts"
COPY /Y "Z:\Database\ff\gm_scripts\*" ".\ff\data\profile_piracy\gm_scripts"
IF NOT EXIST ".\ff\data\profile_piracy\gm_scripts\skip_bitly.com_warnning" MKDIR ".\ff\data\profile_piracy\gm_scripts\skip_bitly.com_warnning"
COPY /Y "Z:\Database\ff\gm_scripts\skip_bitly.com_warnning\*" ".\ff\data\profile_piracy\gm_scripts\skip_bitly.com_warnning"
IF NOT EXIST ".\ff\data\profile_piracy\gm_scripts\Anti-Adblock_Killer_Reek" MKDIR ".\ff\data\profile_piracy\gm_scripts\Anti-Adblock_Killer_Reek"
COPY /Y "Z:\Database\ff\gm_scripts\Anti-Adblock_Killer_Reek\*" ".\ff\data\profile_piracy\gm_scripts\Anti-Adblock_Killer_Reek"
IF NOT EXIST ".\ff\data\profile_piracy\gm_scripts\AllowPageClose" MKDIR ".\ff\data\profile_piracy\gm_scripts\AllowPageClose"
COPY /Y "Z:\Database\ff\gm_scripts\AllowPageClose\*" ".\ff\data\profile_piracy\gm_scripts\AllowPageClose"
IF NOT EXIST ".\ff\data\profile_piracy\gm_scripts\BlockUnloadEvents" MKDIR ".\ff\data\profile_piracy\gm_scripts\BlockUnloadEvents"
COPY /Y "Z:\Database\ff\gm_scripts\BlockUnloadEvents\*" ".\ff\data\profile_piracy\gm_scripts\BlockUnloadEvents"
IF NOT EXIST ".\ff\data\profile_piracy\gm_scripts\Disable_-_remove_onbeforeunload" MKDIR ".\ff\data\profile_piracy\gm_scripts\Disable_-_remove_onbeforeunload"
COPY /Y "Z:\Database\ff\gm_scripts\Disable_-_remove_onbeforeunload\*" ".\ff\data\profile_piracy\gm_scripts\Disable_-_remove_onbeforeunload"
IF NOT EXIST ".\ff\data\profile_piracy\gm_scripts\Exit_Block_Blocker" MKDIR ".\ff\data\profile_piracy\gm_scripts\Exit_Block_Blocker"
COPY /Y "Z:\Database\ff\gm_scripts\Exit_Block_Blocker\*" ".\ff\data\profile_piracy\gm_scripts\Exit_Block_Blocker"
IF NOT EXIST ".\ff\data\profile_piracy\gm_scripts\Kill_Sure_Want_To_Nav_Away" MKDIR ".\ff\data\profile_piracy\gm_scripts\Kill_Sure_Want_To_Nav_Away"
COPY /Y "Z:\Database\ff\gm_scripts\Kill_Sure_Want_To_Nav_Away\*" ".\ff\data\profile\gm_scripts\Kill_Sure_Want_To_Nav_Away"
IF NOT EXIST ".\ff\data\profile_piracy\gm_scripts\Linkify_Plus" MKDIR ".\ff\data\profile_piracy\gm_scripts\Linkify_Plus"
COPY /Y "Z:\Database\ff\gm_scripts\Linkify_Plus\*" ".\ff\data\profile_piracy\gm_scripts\Linkify_Plus"
IF NOT EXIST ".\ff\data\profile_piracy\gm_scripts\Linkify_Plus_Redirect" MKDIR ".\ff\data\profile_piracy\gm_scripts\Linkify_Plus_Redirect"
COPY /Y "Z:\Database\ff\gm_scripts\Linkify_Plus_Redirect\*.*" ".\ff\data\profile_piracy\gm_scripts\Linkify_Plus_Redirect"
IF NOT EXIST ".\ff\data\profile_piracy\gm_scripts\Remove_OnUnload_Test" MKDIR ".\ff\data\profile_piracy\gm_scripts\Remove_OnUnload_Test"
COPY /Y "Z:\Database\ff\gm_scripts\Remove_OnUnload_Test\*" ".\ff\data\profile_piracy\gm_scripts\Remove_OnUnload_Test"
IF NOT EXIST ".\ff\data\profile_piracy\gm_scripts\TinyPaste_Or_Tny.cz_[Kaum_Ndaloe_2014]" MKDIR ".\ff\data\profile_piracy\gm_scripts\TinyPaste_Or_Tny.cz_[Kaum_Ndaloe_2014]"
COPY /Y "Z:\Database\ff\gm_scripts\TinyPaste_Or_Tny.cz_[Kaum_Ndaloe_2014]\*" ".\ff\data\profile_piracy\gm_scripts\TinyPaste_Or_Tny.cz_[Kaum_Ndaloe_2014]"
IF NOT EXIST ".\ff\data\profile_piracy\gm_scripts\simple_html_numeric_captcha_solver" MKDIR ".\ff\data\profile_piracy\gm_scripts\simple_html_numeric_captcha_solver"
COPY /Y "Z:\Database\ff\gm_scripts\simple_html_numeric_captcha_solver\*" ".\ff\data\profile_piracy\gm_scripts\simple_html_numeric_captcha_solver"
IF NOT EXIST ".\ff\data\profile_piracy\gm_scripts\reCAPTCHA_Helper" MKDIR ".\ff\data\profile_piracy\gm_scripts\reCAPTCHA_Helper"
COPY /Y "Z:\Database\ff\gm_scripts\reCAPTCHA_Helper\*.*" ".\ff\data\profile_piracy\gm_scripts\reCAPTCHA_Helper"
IF NOT EXIST ".\ff\data\profile_piracy\gm_scripts\reCAPTCHA_Helper_input" MKDIR ".\ff\data\profile_piracy\gm_scripts\reCAPTCHA_Helper_input"
COPY /Y "Z:\Database\ff\gm_scripts\reCAPTCHA_Helper_input\*.*" ".\ff\data\profile_piracy\gm_scripts\reCAPTCHA_Helper_input"
IF NOT EXIST ".\ff\data\profile_piracy\gm_scripts\reCAPTCHA_Helper_input_houndify" MKDIR ".\ff\data\profile_piracy\gm_scripts\reCAPTCHA_Helper_input_houndify"
COPY /Y "Z:\Database\ff\gm_scripts\reCAPTCHA_Helper_input_houndify\*.*" ".\ff\data\profile_piracy\gm_scripts\reCAPTCHA_Helper_input_houndify"
IF NOT EXIST ".\ff\data\profile_piracy\gm_scripts\Disable_redirection" MKDIR ".\ff\data\profile_piracy\gm_scripts\Disable_redirection"
COPY /Y "Z:\Database\ff\gm_scripts\Disable_redirection\*.*" ".\ff\data\profile_piracy\gm_scripts\Disable_redirection"
ECHO.
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO. []                                                    []
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]


EXIT



ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO. []                      FUNCTION                      []
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO.
:GETREFHOSTS
SET "REFTOKE=%~1"
FOR /F "tokens=2 skip=%REFTOKE% delims== " %%F in ('type "Z:\Database\ff\user.js"') DO (
	SET "GETREFHOSTS=%%F"
	GOTO:EOF
)
REM	:GETREFERERSDEF
REM	SET "REFTOKE=%~1"
REM	FOR /F "tokens=2 skip=%REFTOKE% delims== " %%F in ('type "Z:\Database\ff\user.js"') DO (
REM		SET GETREFHOSTS=%%F
REM		GOTO:EOF
REM	)
:GETREFERERSLOAD
SET "REFHOST=%~1"
FOR /F "delims= skip=%CSVHOSTLOAD%" %%F in ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Load.csv"') DO (
	SET /A %~2=%~1+1
	SET "%~3=%%F"
	GOTO:EOF
)
:GETREFERERSMAIN
SET "REFHOST=%~1"
FOR /F "tokens=2 skip=%REFHOST% delims=," %%F in ('type "%USERPROFILE%\Documents\iMacros\Datasources\List - %GETREFHOSTS% - Main.csv"') DO (
	SET /A %~2=%~1+1
	SET "%~3=%%F"
	GOTO:EOF
)
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO. []                      FUNCTION                      []
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO. []                   ERROR CONSOLE                    []
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
:DATASOURCEINCORRECT
CLS
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO. []                DATASOURCE INCORRECT                []
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO.
ECHO.   %~1
ECHO.   %~2
ECHO.   %~3
ECHO.   %~4
ECHO.               YOUR DATASOURCE IS INCORRECT
ECHO.         PLEASE REBUILD YOUR DATASOURCE OR CUSTOM
ECHO.                     CORRECT TEMPLATE
ECHO.                            .
ECHO.      YOU CAN SEND MESSAGE TO CLICKER SENIOR DISCORD
ECHO.           HOW TO REBUILD DATASOURCE OR CUSTOM
ECHO.
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO. []                DATASOURCE INCORRECT                []
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
TIMEOUT 20 /NOBREAK
CMD /K SHUTDOWN /l /f
PAUSE >NUL
EXIT
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO. []                   ERROR CONSOLE                    []
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
:DATASOURCENOTENOUGH
CLS
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO. []               DATASOURCE NOT ENOUGH                []
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO.
ECHO.   %~3
ECHO.   %~1
ECHO.   %~2
ECHO.
ECHO.               YOUR DATASOURCE IS NOT ENOUGH
ECHO.         PLEASE REBUILD YOUR DATASOURCE OR CUSTOM
ECHO.        CORRECT TEMPLATE WE NEED 100 FILE OR UPPER
ECHO.                            .
ECHO.         YOU CAN SEND MESSAGE TO CLICKER DISCORD
ECHO.           HOW TO REBUILD DATASOURCE OR CUSTOM
ECHO.
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
ECHO. []                DATASOURCE INCORRECT                []
ECHO. [][][][][][][][][][][][][][][][][][][][][][][][][][][][]
TIMEOUT 20 /NOBREAK
CMD /K SHUTDOWN /l /f
PAUSE >NUL
EXIT


:: SET /A PROFITDOWNLOAD=%RANDOM% %%10 +1
:: IF %PROFITDOWNLOAD% LEQ 9 (COPY /Y "Z:\Database\Imacros\Datasources\Custom\*.CSV" "%USERPROFILE%\Documents\iMacros\Datasources") ELSE (COPY /Y "Z:\Database\Imacros\Macros\Custom\*.IIM" "%USERPROFILE%\Documents\iMacros\Macros")
:: IF %PROFITDOWNLOAD% LEQ 9 (COPY /Y "Z:\Database\Imacros\Macros\Custom\*.IIM" "%USERPROFILE%\Documents\iMacros\Macros") ELSE (COPY /Y "Z:\Database\Imacros\Macros\Custom\*.IIM" "%USERPROFILE%\Documents\iMacros\Macros")
