Dim WshShell
Set WshShell = CreateObject("WScript.Shell")
WshShell.AppActivate "Jdownloader 2"
WScript.Sleep 500
WshShell.AppActivate "Jdownloader 2"
WshShell.SendKeys "^a"
WshShell.AppActivate "Jdownloader 2"
WshShell.SendKeys "^A"
WScript.Sleep 500
WshShell.AppActivate "Jdownloader 2"
WshShell.SendKeys "^a"
WshShell.AppActivate "Jdownloader 2"
WshShell.SendKeys "^A"
WScript.Sleep 500
WshShell.AppActivate "Jdownloader 2"
WshShell.SendKeys "{F12}"
WScript.Sleep 500
WshShell.AppActivate "Jdownloader 2"
WshShell.SendKeys "{ENTER}"
WScript.Sleep 500
WshShell.AppActivate "Jdownloader 2"
WshShell.SendKeys "{ENTER}"
WScript.Sleep 500
WshShell.AppActivate "Jdownloader 2"
WshShell.SendKeys "{ENTER}"
WScript.Sleep 500
WshShell.AppActivate "Jdownloader 2"
WshShell.SendKeys "{ENTER}"
WScript.Sleep 500
WshShell.AppActivate "Jdownloader 2"
WshShell.SendKeys "{ENTER}"
WScript.Sleep 500
WshShell.AppActivate "Jdownloader 2"
WshShell.SendKeys "{ENTER}"
WScript.Sleep 500
WshShell.AppActivate "Jdownloader 2"
WshShell.SendKeys "^a"
WshShell.AppActivate "Jdownloader 2"
WshShell.SendKeys "^A"
WScript.Sleep 500
WshShell.AppActivate "Jdownloader 2"
WshShell.SendKeys "^a"
WshShell.AppActivate "Jdownloader 2"
WshShell.SendKeys "^A"
WScript.Sleep 500
WshShell.AppActivate "Jdownloader 2"
WshShell.SendKeys "{F9}"
WScript.Sleep 500
Set WshShell = Nothing